# Game settings
game_settings:
  num_rounds: 3
  core_config_path: "configs/core.yaml"
  theme_config_path: "configs/themes/fantasy/fantasy.yaml"
  edition_config_path: "configs/themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow.yaml"
  manual: "MOTIVE_MANUAL.md"

# List of AI players
players:
  - name: "Arion"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Lyra"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Kael"
    provider: "google"
    model: "gemini-2.5-flash"
