# Game settings
game_settings:
  num_rounds: 3
  theme: "Fantasy"
  edition: "HearthAndShadow"
  manual: "MOTIVE_MANUAL.md"

# List of AI players
players:
  - name: "Arion"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Lyra"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Kael"
    provider: "google"
    model: "gemini-2.5-flash"
