# Hearth and Shadow v2 Configuration
# This is the main v2 config file for the H&S edition

includes:
  - "../../../../core_actions.yaml"
  - "hearth_and_shadow_actions.yaml"
  - "hearth_and_shadow_rooms.yaml"
  - "hearth_and_shadow_motive_rooms.yaml"
  - "hearth_and_shadow_characters.yaml"
  - "hearth_and_shadow_objects.yaml"
  - "hearth_and_shadow_motive_objects.yaml"

game_settings:
  num_rounds: 20
  initial_ap_per_turn: 40
  manual: "../../../docs/MANUAL.md"
  log_path: "fantasy/hearth_and_shadow/{game_id}"

players:
  - name: "Player_1"
    provider: "google"
    model: "gemini-2.5-flash"
  - name: "Player_2"
    provider: "google"
    model: "gemini-2.5-flash"
