includes:
- ../../fantasy.yaml
- hearth_and_shadow_rooms.yaml
- hearth_and_shadow_characters.yaml
- hearth_and_shadow_objects.yaml
testid: hearth_and_shadow
name: Hearth and Shadow
theme_id: fantasy
edition_id: hearth_and_shadow
