# Include the theme and hearth and shadow edition components (V2 Native)
includes:
  - "../../fantasy.yaml"
  - "hearth_and_shadow_rooms_v2.yaml"
  - "hearth_and_shadow_characters_v2.yaml"
  - "hearth_and_shadow_objects_v2.yaml"
  - "hearth_and_shadow_actions.yaml"  # Keep v1 for now since it's empty

testid: hearth_and_shadow_v2
name: Hearth and Shadow (V2)
theme_id: fantasy
edition_id: hearth_and_shadow
