# Hearth and Shadow edition characters - Blackwater Town (Sim V2 Enhanced)
# This file showcases the new sim_v2 features: status effects, triggers, affordances, and dynamic properties

characters:
  detective_thorne:
    id: detective_thorne
    name: Detective James Thorne
    backstory: |
      A former city guard turned private investigator, James Thorne came to Blackwater 
      to investigate the mysterious disappearances. He's methodical, observant, and 
      determined to uncover the truth. His partner was killed during their last case, 
      and he carries both the guilt and the determination to bring justice to those 
      responsible for the growing darkness in the town.
    motive: avenge_partner
    # Sim V2: Enhanced properties with status effects
    properties:
      investigation_skill: 8
      reputation: "good"
      corruption_level: 0
      evil_alignment: false
      # Sim V2: Base stats that can be modified by status effects
      strength: 6
      intelligence: 9
      constitution: 7
      wisdom: 8
      charisma: 5
      # Sim V2: Triggers - detective reacts to discoveries
      triggers:
        - trigger_id: "partner_memory"
          condition: "cult_evidence_found == true"
          effects:
            - set_property: {target: "self", property: "determination", value: "determination + 2"}
            - emit_event: {event: "partner_avenged", data: {evidence_type: "cult", location: "current"}}
        - trigger_id: "corruption_resistance"
          condition: "corruption_level > 3"
          effects:
            - set_property: {target: "self", property: "investigation_skill", value: "investigation_skill - 1"}
            - set_property: {target: "self", property: "description", value: "You feel the darkness creeping into your mind, clouding your judgment."}
      # Sim V2: Affordances - detective can investigate
      affordances:
        - action: "investigate"
          condition: "investigation_skill > 0"
          effects:
            - emit_event: {event: "investigation_started", data: {skill_level: "investigation_skill", location: "current"}}
            - set_property: {target: "self", property: "investigation_skill", value: "investigation_skill - 1"}
          description: "Investigate the current location for clues"
        - action: "question_witness"
          condition: "investigation_skill > 2"
          effects:
            - emit_event: {event: "witness_questioned", data: {skill_level: "investigation_skill", reliability: "high"}}
          description: "Question a witness about recent events"
    # Sim V2: Status Effects - detective can gain various temporary effects
    status_effects:
      - name: "investigation_fatigue"
        duration_turns: 3
        stacking_policy: "refresh"
        source: "action"
        overlays:
          intelligence: -1
          investigation_skill: -1
        description: "Mental exhaustion from intense investigation"
      - name: "cult_corruption"
        duration_turns: 5
        stacking_policy: "no_stack"
        source: "action"
        overlays:
          corruption_level: 1
          evil_alignment: true
          wisdom: -2
        description: "Dark influence from exposure to cult artifacts"
      - name: "partner_memory"
        duration_turns: null  # Permanent until manually removed
        stacking_policy: "no_stack"
        source: "inherent"
        overlays:
          investigation_skill: 2
          strength: 1
        description: "Motivation from memories of your fallen partner"

  bella_hoarder:
    id: bella_hoarder
    name: Bella the Hoarder
    backstory: |
      Bella is a local resident who has become obsessed with collecting items, 
      especially those related to the mysterious events in town. She believes 
      that by gathering enough evidence, she can piece together what's happening 
      and protect herself from the growing darkness. Her hoarding has become 
      more extreme as the cult's influence grows.
    motive: hoard_evidence
    # Sim V2: Enhanced properties with hoarding mechanics
    properties:
      hoarding_skill: 6
      collection_size: 0
      paranoia_level: 3
      corruption_level: 0
      # Sim V2: Status effects - hoarding affects behavior
      status_effects:
        - effect_id: "hoarding_obsession"
          condition: "collection_size > 10"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "self", property: "hoarding_skill", value: "hoarding_skill + 1"}
            - set_property: {target: "self", property: "paranoia_level", value: "paranoia_level + 1"}
        - effect_id: "collection_anxiety"
          condition: "collection_size < 5"
          duration: 2
          effects:
            - set_property: {target: "self", property: "hoarding_skill", value: "hoarding_skill + 2"}
            - set_property: {target: "self", property: "description", value: "You feel anxious about your small collection and need to find more items."}
      # Sim V2: Triggers - hoarding affects relationships
      triggers:
        - trigger_id: "collection_pride"
          condition: "collection_size > 20"
          effects:
            - set_property: {target: "self", property: "confidence", value: "confidence + 3"}
            - emit_event: {event: "collection_complete", data: {size: "collection_size", type: "evidence"}}
        - trigger_id: "hoarding_paranoia"
          condition: "paranoia_level > 7"
          effects:
            - set_property: {target: "self", property: "trust_level", value: "trust_level - 2"}
            - set_property: {target: "self", property: "description", value: "You're becoming increasingly paranoid about others trying to steal your collection."}
      # Sim V2: Affordances - hoarding actions
      affordances:
        - action: "collect_item"
          condition: "hoarding_skill > 0"
          effects:
            - set_property: {target: "self", property: "collection_size", value: "collection_size + 1"}
            - emit_event: {event: "item_collected", data: {collection_size: "collection_size", item_type: "evidence"}}
          description: "Collect an item for your evidence hoard"
        - action: "organize_collection"
          condition: "collection_size > 5"
          effects:
            - set_property: {target: "self", property: "hoarding_skill", value: "hoarding_skill + 1"}
            - set_property: {target: "self", property: "paranoia_level", value: "paranoia_level - 1"}
          description: "Organize your collection to reduce paranoia"

  mayor_blackwater:
    id: mayor_blackwater
    name: Mayor Blackwater
    backstory: |
      The mayor of Blackwater, a man who has seen his town slowly decline into 
      darkness and fear. He's torn between maintaining order and acknowledging 
      the supernatural threats that plague his town. He knows more than he lets on 
      about the cult's activities but fears the consequences of revealing the truth.
    motive: protect_town
    # Sim V2: Enhanced properties with political mechanics
    properties:
      authority_level: 9
      town_knowledge: 7
      corruption_level: 2
      cult_awareness: 5
      # Sim V2: Status effects - mayor's authority affects town
      status_effects:
        - effect_id: "mayoral_authority"
          condition: "authority_level > 5"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "town", property: "order_level", value: "order_level + 1"}
            - set_property: {target: "town", property: "fear_level", value: "fear_level - 1"}
        - effect_id: "cult_corruption"
          condition: "corruption_level > 3"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "self", property: "authority_level", value: "authority_level - 1"}
            - set_property: {target: "town", property: "cult_influence", value: "cult_influence + 1"}
      # Sim V2: Triggers - mayor reacts to town events
      triggers:
        - trigger_id: "town_crisis"
          condition: "missing_persons > 10"
          effects:
            - set_property: {target: "self", property: "authority_level", value: "authority_level - 2"}
            - emit_event: {event: "mayoral_crisis", data: {missing_persons: "missing_persons", authority_loss: 2}}
        - trigger_id: "cult_revelation"
          condition: "cult_evidence_public == true"
          effects:
            - set_property: {target: "self", property: "cult_awareness", value: "cult_awareness + 3"}
            - set_property: {target: "self", property: "description", value: "The mayor looks shaken by the revelation of cult activity in his town."}
      # Sim V2: Affordances - mayor can take action
      affordances:
        - action: "declare_emergency"
          condition: "authority_level > 5 AND missing_persons > 5"
          effects:
            - set_property: {target: "town", property: "emergency_status", value: true}
            - emit_event: {event: "emergency_declared", data: {authority: "authority_level", reason: "missing_persons"}}
          description: "Declare a town emergency due to missing persons"
        - action: "reveal_cult_knowledge"
          condition: "cult_awareness > 7 AND authority_level > 3"
          effects:
            - set_property: {target: "town", property: "cult_evidence_public", value: true}
            - set_property: {target: "self", property: "authority_level", value: "authority_level - 1"}
            - emit_event: {event: "cult_revelation", data: {source: "mayor", authority_cost: 1}}
          description: "Reveal what you know about the cult to the town"

  father_marcus:
    id: father_marcus
    name: Father Marcus
    backstory: |
      The town's priest and spiritual leader, Father Marcus has been fighting 
      against the growing darkness in Blackwater. He's aware of the cult's 
      activities and has been working to protect the town's spiritual well-being. 
      He possesses ancient knowledge about combating evil forces and can provide 
      guidance to those seeking to fight the darkness.
    motive: spiritual_protection
    # Sim V2: Enhanced properties with spiritual mechanics
    properties:
      holy_power: 10
      spiritual_knowledge: 9
      corruption_resistance: 8
      cult_knowledge: 6
      # Sim V2: Status effects - priest's holy power affects town
      status_effects:
        - effect_id: "holy_protection"
          condition: "holy_power > 5"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "town", property: "holy_protection", value: true}
            - set_property: {target: "town", property: "cult_influence", value: "cult_influence - 1"}
        - effect_id: "spiritual_guidance"
          condition: "spiritual_knowledge > 7"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "town", property: "hope_level", value: "hope_level + 1"}
            - set_property: {target: "town", property: "fear_level", value: "fear_level - 1"}
      # Sim V2: Triggers - priest reacts to spiritual threats
      triggers:
        - trigger_id: "cult_activity_detected"
          condition: "cult_activity > 5"
          effects:
            - set_property: {target: "self", property: "holy_power", value: "holy_power + 2"}
            - emit_event: {event: "spiritual_alert", data: {cult_activity: "cult_activity", holy_response: "increased"}}
        - trigger_id: "town_despair"
          condition: "hope_level < 3"
          effects:
            - set_property: {target: "self", property: "holy_power", value: "holy_power - 1"}
            - set_property: {target: "self", property: "description", value: "Father Marcus looks weary from fighting the growing darkness."}
      # Sim V2: Affordances - priest can perform spiritual actions
      affordances:
        - action: "bless_location"
          condition: "holy_power > 3"
          effects:
            - set_property: {target: "location", property: "holy_blessed", value: true}
            - set_property: {target: "location", property: "cult_influence", value: "cult_influence - 2"}
            - emit_event: {event: "location_blessed", data: {holy_power: "holy_power", location: "current"}}
          description: "Bless the current location to reduce cult influence"
        - action: "exorcise_evil"
          condition: "holy_power > 7 AND cult_presence == true"
          effects:
            - set_property: {target: "location", property: "cult_presence", value: false}
            - set_property: {target: "self", property: "holy_power", value: "holy_power - 3"}
            - emit_event: {event: "evil_exorcised", data: {holy_power_cost: 3, location: "current"}}
          description: "Perform an exorcism to remove evil presence"

  the_raven:
    id: the_raven
    name: The Raven
    backstory: |
      A mysterious figure who appears to be connected to the cult's activities. 
      The Raven is known for their cryptic messages and shadowy presence. They 
      seem to know more about the town's dark secrets than anyone else, but 
      their motives are unclear. Are they a cult member, a victim, or something 
      else entirely?
    motive: mysterious_agenda
    # Sim V2: Enhanced properties with mysterious mechanics
    properties:
      mystery_level: 10
      cult_connection: 8
      information_value: 9
      trustworthiness: 2
      # Sim V2: Status effects - raven's mystery affects interactions
      status_effects:
        - effect_id: "mysterious_presence"
          condition: "mystery_level > 7"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "town", property: "mystery_level", value: "mystery_level + 1"}
            - set_property: {target: "town", property: "fear_level", value: "fear_level + 1"}
        - effect_id: "information_broker"
          condition: "information_value > 5"
          duration: -1  # Permanent
          effects:
            - set_property: {target: "town", property: "information_flow", value: "information_flow + 1"}
      # Sim V2: Triggers - raven reacts to investigation
      triggers:
        - trigger_id: "investigation_detected"
          condition: "player_investigating == true"
          effects:
            - set_property: {target: "self", property: "mystery_level", value: "mystery_level + 1"}
            - emit_event: {event: "raven_warning", data: {mystery_level: "mystery_level", threat: "increased"}}
        - trigger_id: "cult_threat_reduced"
          condition: "cult_threat < 3"
          effects:
            - set_property: {target: "self", property: "trustworthiness", value: "trustworthiness + 2"}
            - set_property: {target: "self", property: "description", value: "The Raven seems less threatening now that the cult's influence has waned."}
      # Sim V2: Affordances - raven can provide information
      affordances:
        - action: "demand_information"
          condition: "mystery_level > 5"
          effects:
            - emit_event: {event: "raven_information", data: {mystery_level: "mystery_level", reliability: "low"}}
            - set_property: {target: "self", property: "mystery_level", value: "mystery_level - 1"}
          description: "Demand information from the Raven"
        - action: "negotiate_with_raven"
          condition: "trustworthiness > 3"
          effects:
            - emit_event: {event: "raven_negotiation", data: {trustworthiness: "trustworthiness", outcome: "favorable"}}
            - set_property: {target: "self", property: "information_value", value: "information_value - 2"}
          description: "Negotiate with the Raven for information"
