# Hearth and Shadow Edition - Blackwater Town Characters with Multiple Motives
# Example of the new motives system where characters have multiple possible motives

characters:
  # The Investigator with multiple possible motives
  detective_thorne:
    id: detective_thorne
    name: Detective James Thorne
    backstory: |
      A former city guard turned private investigator, James Thorne arrived in Blackwater 
      three months ago to investigate the mysterious disappearances. His sharp mind and 
      keen observational skills have made him a valuable asset to the town, but his 
      relentless pursuit of the truth has made him enemies among those who prefer to 
      keep their secrets hidden. He carries a worn notebook filled with clues and 
      suspects, and his weathered face tells the story of many sleepless nights spent 
      on the case. His partner was killed by the cult, and he has a sick daughter who 
      needs expensive medicine - creating a dangerous vulnerability that the cult could exploit.
    motives:
      - id: investigate_mayor
        description: "Uncover the truth behind the mayor's disappearance and bring the cult to justice. Protect the remaining townsfolk from further harm."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: found_mayor
          - type: player_has_tag
            tag: cult_exposed
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: mayor_dead
          - type: player_has_tag
            tag: cult_succeeded
      - id: protect_daughter
        description: "Protect your sick daughter by finding the medicine she needs and keeping her safe from the cult."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: medicine_found
          - type: player_has_tag
            tag: daughter_safe
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: daughter_taken
          - type: player_has_tag
            tag: daughter_dead
      - id: avenge_partner
        description: "Avenge your murdered partner by destroying the cult and bringing their killers to justice."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: partner_avenged
          - type: player_has_tag
            tag: cult_destroyed
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: cult_escaped
          - type: player_has_tag
            tag: partner_forgotten
    aliases: [james, detective, thorn, investigator, sleuth]

  # The Troubled Priest with multiple possible motives
  father_marcus:
    id: father_marcus
    name: Father Marcus
    backstory: |
      The priest of Sacred Heart Church, Father Marcus has served the community for over 
      twenty years. Recently, he has become increasingly troubled and distracted, often 
      found in the confession booth or staring at the crypt entrance. His once-strong 
      faith has been shaken by the evil he has witnessed, and he carries a terrible 
      secret that weighs heavily on his soul. The cult forced him to perform a dark 
      ritual three months ago, threatening to kill his congregation if he refused. 
      Now he knows their plans but revealing them would endanger everyone he loves. 
      His internal struggle between duty and fear, truth and protection, drives his 
      every action. He prays for divine guidance but fears he has already damned himself.
    motives:
      - id: protect_flock
        description: "Protect your congregation from the growing darkness and keep them safe from the cult's influence."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: congregation_safe
          - type: player_has_tag
            tag: church_protected
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: congregation_corrupted
          - type: player_has_tag
            tag: church_desecrated
      - id: seek_redemption
        description: "Seek redemption for your past failures and find the strength to confront the evil that threatens your town."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: redemption_found
          - type: player_has_tag
            tag: faith_restored
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: faith_lost
          - type: player_has_tag
            tag: damned_forever
      - id: expose_cult_safely
        description: "Expose the cult's activities without endangering innocent lives, revealing their plans to the right people."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: cult_exposed_safely
          - type: player_has_tag
            tag: innocents_protected
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: innocents_harmed
          - type: player_has_tag
            tag: cult_warned
    aliases: [marcus, father, priest, cleric, confessor, shepherd]

  # The Guild Master with multiple possible motives
  guild_master_elena:
    id: guild_master_elena
    name: Guild Master Elena
    backstory: |
      A seasoned adventurer who retired to become the leader of Blackwater's Adventurer's 
      Guild, Elena has seen her share of battles and knows the value of information. 
      Her desk is covered with reports and correspondence, and she maintains a network 
      of contacts throughout the region. She has been quietly investigating the 
      disappearances on her own, using her guild's resources to gather intelligence. 
      Her calm demeanor masks a fierce determination to protect her town and her people.
    motives:
      - id: coordinate_defense
        description: "Coordinate the town's defense against the cult threat and train new adventurers to fight the darkness."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: town_defended
          - type: player_has_tag
            tag: adventurers_trained
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: town_fallen
          - type: player_has_tag
            tag: guild_destroyed
      - id: gather_intelligence
        description: "Gather intelligence about the cult's plans and activities to help the town prepare for their next move."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: cult_plans_discovered
          - type: player_has_tag
            tag: intelligence_network_active
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: intelligence_compromised
          - type: player_has_tag
            tag: cult_escaped
      - id: restore_guild_reputation
        description: "Restore the guild's reputation and bring in new members to strengthen the town's defenses."
        success_conditions:
          - operator: "AND"
          - type: player_has_tag
            tag: guild_reputation_restored
          - type: player_has_tag
            tag: new_members_recruited
        failure_conditions:
          - operator: "OR"
          - type: player_has_tag
            tag: guild_disbanded
          - type: player_has_tag
            tag: reputation_ruined
    aliases: [elena, guild, master, leader, commander, veteran]
