entity_definitions:
  notice_board:
    behaviors:
    - object
    properties:
      name: Notice Board
      description: A wooden board covered with various notices, posters, and announcements.
      readable: true
      text: Various town announcements and missing person posters are posted here.
  broken_fountain:
    behaviors:
    - object
    properties:
      name: Broken Fountain
      description: A once-beautiful stone fountain, now cracked and dry.
      immovable: true
      size: large
  bar:
    behaviors:
    - object
    properties:
      name: Bar
      description: A long wooden bar where drinks are served.
      immovable: true
      size: large
  suspicious_character:
    behaviors:
    - object
    properties:
      name: Suspicious Character
      description: A figure who seems to be watching everything carefully.
      immovable: true
      size: medium
  quest_board:
    behaviors:
    - object
    properties:
      name: Quest Board
      description: A board covered with various quests and missions.
      readable: true
      text: Various quests and bounties are posted here, including some related to
        recent disappearances.
  guild_master_desk:
    behaviors:
    - object
    properties:
      name: Guild Master's Desk
      description: A massive oak desk covered with reports and correspondence.
      immovable: true
      size: large
      readable: true
      text: The desk contains various reports and maps that might contain valuable
        information.
  weapon_rack:
    behaviors:
    - object
    properties:
      name: Weapon Rack
      description: A rack displaying various weapons and armor.
      immovable: true
      size: large
  stolen_goods:
    behaviors:
    - object
    properties:
      name: Stolen Goods
      description: Various stolen items and contraband.
      immovable: true
      size: medium
  secret_documents:
    behaviors:
    - object
    properties:
      name: Secret Documents
      description: A collection of documents that might contain valuable information.
      readable: true
      text: These documents contain information about the town's troubles and recent
        activities.
  raven_chair:
    behaviors:
    - object
    properties:
      name: The Raven's Chair
      description: A high-backed chair where the leader of the thieves' guild sits.
      immovable: true
      size: large
  confession_booth:
    behaviors:
    - object
    properties:
      name: Confession Booth
      description: A wooden booth where the faithful come to confess their sins.
      immovable: true
      size: medium
  crypt_entrance:
    behaviors:
    - object
    properties:
      name: Crypt Entrance
      description: A hidden entrance to the underground crypt.
      immovable: true
      size: medium
  mausoleum:
    behaviors:
    - object
    properties:
      name: Mausoleum
      description: A large stone mausoleum with doors that seem to be slightly ajar.
      immovable: true
      size: huge
  fresh_graves:
    behaviors:
    - object
    properties:
      name: Fresh Graves
      description: Several graves that appear to have been recently dug.
      immovable: true
      size: large
  suspicious_footprints:
    behaviors:
    - object
    properties:
      name: Suspicious Footprints
      description: Footprints in the soft earth that don't seem to belong to any normal
        visitor.
      immovable: true
      size: small
  vault:
    behaviors:
    - object
    properties:
      name: Vault
      description: A massive steel vault that seems to be open more often than it
        should be.
      immovable: true
      size: huge
  ledgers:
    behaviors:
    - object
    properties:
      name: Bank Ledgers
      description: Financial records that might contain clues about mysterious transactions.
      readable: true
      text: These ledgers contain financial records that might reveal clues about
        the mysterious withdrawals.
  guard_post:
    behaviors:
    - object
    properties:
      name: Guard Post
      description: A security station that seems to be unmanned more often than not.
      immovable: true
      size: medium
  merchant_stalls:
    behaviors:
    - object
    properties:
      name: Merchant Stalls
      description: Various stalls where merchants sell their wares.
      immovable: true
      size: large
  suspicious_merchants:
    behaviors:
    - object
    properties:
      name: Suspicious Merchants
      description: Merchants who seem to be involved in more than just legitimate
        trade.
      immovable: true
      size: medium
  hidden_alleyways:
    behaviors:
    - object
    properties:
      name: Hidden Alleyways
      description: Narrow passages between buildings that lead to secret meeting places.
      immovable: true
      size: medium
  cult_symbols:
    behaviors:
    - object
    properties:
      name: Cult Symbols
      description: Dark, unsettling symbols painted on walls and carved into surfaces.
      readable: true
      immovable: true
      size: small
      text: The symbols seem to pulse with dark energy. They appear to be some form
        of ancient writing, but the meaning is unclear. However, they all seem to
        point toward the same direction - deeper into the underground.
  evidence_activity:
    behaviors:
    - object
    properties:
      name: Evidence of Recent Activity
      description: Signs that someone has been using these tunnels recently.
      immovable: true
      size: small
  secret_doors:
    behaviors:
    - object
    properties:
      name: Secret Doors
      description: Hidden entrances and exits that lead to various parts of the town.
      immovable: true
      size: medium
  cult_altar:
    behaviors:
    - object
    properties:
      name: Cult Altar
      description: A dark altar covered with cult artifacts and evidence of recent
        rituals.
      immovable: true
      size: large
  prisoner_cells:
    behaviors:
    - object
    properties:
      name: Prisoner Cells
      description: Cells where the cult keeps their prisoners.
      immovable: true
      size: large
  cult_artifacts:
    behaviors:
    - object
    properties:
      name: Cult Artifacts
      description: Various dark objects and artifacts used in the cult's rituals.
      immovable: true
      size: medium
  forest_watchers:
    behaviors:
    - object
    properties:
      name: Forest Watchers
      description: The forest itself seems to be watching and waiting.
      immovable: true
      size: medium
  mayors_journal:
    behaviors:
    - object
    properties:
      name: Mayor's Journal
      description: A leather-bound journal belonging to the missing mayor, filled
        with his private thoughts and observations.
      readable: true
      pickupable: true
      size: small
      text: The cult's influence grows stronger each day. I fear they have infiltrated
        the town guard. Father Marcus seems troubled - I must speak with him. The
        disappearances are not random - they're targeting specific people. I've hidden
        evidence in the bank vault. If something happens to me, find Detective Thorne.
  cult_ritual_book:
    behaviors:
    - object
    properties:
      name: Cult Ritual Book
      description: A dark, leather-bound tome filled with ancient symbols and blood-stained
        pages.
      readable: true
      pickupable: true
      size: medium
      text: 'The Shadowed Hand seeks to summon the Dark Lord through blood sacrifice.
        The ritual requires seven pure souls, taken during the new moon. The mayor
        was the first - his blood opened the gateway. The next six must be taken in
        sequence: the priest, the warrior, the merchant, the child, the innocent,
        and the betrayer.'
  missing_persons_effects:
    behaviors:
    - object
    properties:
      name: Personal Effects
      description: A collection of personal items belonging to the missing townsfolk.
      readable: true
      pickupable: true
      size: small
      text: Letters, jewelry, and small trinkets. Each item tells a story of a life
        interrupted. A child's doll, a wedding ring, a merchant's ledger. All taken
        from their owners before they disappeared.
  cult_members_confession:
    behaviors:
    - object
    properties:
      name: Cult Member's Confession
      description: A handwritten confession found in the church records.
      readable: true
      pickupable: true
      size: small
      text: I was forced to join the Shadowed Hand. They threatened my family. The
        cult is planning something big - a ritual that will change everything. They
        have people in high places. I can't say more, but the mayor knows too much.
        They're coming for him next.
  fresh_evidence:
    behaviors:
    - object
    properties:
      name: Fresh Evidence
      description: Recently disturbed earth and strange markings.
      readable: true
      immovable: true
      size: medium
      text: The earth has been recently disturbed. Strange symbols are carved into
        the ground, still wet with what appears to be blood. Footprints lead away
        from the site - someone was here recently.
  suspicious_sounds:
    behaviors:
    - object
    properties:
      name: Suspicious Sounds
      description: Strange noises coming from underground.
      readable: true
      immovable: true
      size: small
      text: Low, chanting voices echo from below. The sound is muffled but unmistakable
        - someone is performing a ritual. The voices seem to be getting louder, more
        urgent.
  missing_items:
    behaviors:
    - object
    properties:
      name: Missing Items
      description: Items that were clearly taken, not lost.
      readable: true
      immovable: true
      size: small
      text: Empty spaces where items once sat. Dust outlines show where objects were
        recently removed. The pattern suggests a systematic search - someone was looking
        for something specific.
  witnessed_abduction:
    behaviors:
    - object
    properties:
      name: Witnessed Abduction
      description: Evidence of a recent abduction.
      readable: true
      immovable: true
      size: medium
      text: Struggle marks on the ground, a torn piece of clothing, and a single drop
        of blood. Someone was taken by force, and recently. The trail leads toward
        the underground tunnels.
  lockpicks:
    behaviors:
    - object
    properties:
      name: Lockpicks
      description: A set of fine metal tools for opening locks.
      pickupable: true
      size: small
      tool_type: lockpicking
  torch:
    behaviors:
    - object
    properties:
      name: Torch
      description: A wooden torch that can be lit to provide light in dark areas.
      pickupable: true
      size: medium
      tool_type: lighting
      fuel: 100
  rope:
    behaviors:
    - object
    properties:
      name: Rope
      description: A sturdy length of rope, useful for climbing or binding.
      pickupable: true
      size: medium
      tool_type: climbing
  investigation_kit:
    behaviors:
    - object
    properties:
      name: Investigation Kit
      description: A small kit containing magnifying glass, tweezers, and evidence
        bags.
      pickupable: true
      size: small
      tool_type: investigation
  crowbar:
    behaviors:
    - object
    properties:
      name: Crowbar
      description: A heavy metal bar useful for prying open doors and crates.
      pickupable: true
      size: medium
      tool_type: prying
  holy_water:
    behaviors:
    - object
    properties:
      name: Holy Water
      description: A small vial of blessed water from the church.
      pickupable: true
      size: small
      tool_type: spiritual
      blessed: true
  eternal_flame:
    behaviors:
    - object
    properties:
      name: Eternal Flame
      description: A small, magical flame that never goes out, symbolizing the town's
        unbreakable spirit.
      immovable: true
      size: small
      magical: true
      hearth_symbol: true
  shadow_crystal:
    behaviors:
    - object
    properties:
      name: Shadow Crystal
      description: A dark crystal that seems to absorb light and warmth, pulsing with
        malevolent energy.
      pickupable: true
      size: small
      magical: true
      shadow_symbol: true
  hearth_stone:
    behaviors:
    - object
    properties:
      name: Hearth Stone
      description: A warm stone that radiates comfort and hope, said to protect against
        dark magic.
      pickupable: true
      size: small
      magical: true
      hearth_symbol: true
  shadow_mirror:
    behaviors:
    - object
    properties:
      name: Shadow Mirror
      description: A dark mirror that shows not your reflection, but the shadows of
        your fears and doubts.
      immovable: true
      size: medium
      magical: true
      shadow_symbol: true
  flame_of_hope:
    behaviors:
    - object
    properties:
      name: Flame of Hope
      description: A small, flickering flame that grows brighter when hope is strong
        and dims when despair takes hold.
      immovable: true
      size: small
      magical: true
      hearth_symbol: true
      responsive: true
  message_board:
    behaviors:
    - object
    properties:
      name: Message Board
      description: A wooden board where characters can leave messages for each other.
      readable: true
      writable: true
      immovable: true
      size: medium
      communication: true
  secret_drop_point:
    behaviors:
    - object
    properties:
      name: Secret Drop Point
      description: A hidden location where anonymous messages can be left and retrieved.
      readable: true
      writable: true
      immovable: true
      size: small
      hidden: true
      communication: true
  pigeon_coop:
    behaviors:
    - object
    properties:
      name: Pigeon Coop
      description: A small coop where carrier pigeons can be used to send private
        messages.
      readable: true
      writable: true
      immovable: true
      size: medium
      communication: true
      private: true
  town_crier:
    behaviors:
    - object
    properties:
      name: Town Crier
      description: A person who makes public announcements throughout the town.
      readable: true
      immovable: true
      size: medium
      communication: true
      public: true
  burning_candle:
    behaviors:
    - object
    properties:
      name: Burning Candle
      description: A candle that burns down over time, creating urgency.
      immovable: true
      size: small
      time_sensitive: true
      fuel: 100
  fresh_footprints:
    behaviors:
    - object
    properties:
      name: Fresh Footprints
      description: Footprints that will disappear as time passes.
      readable: true
      immovable: true
      size: small
      time_sensitive: true
      text: Fresh footprints in the dust. They appear to be recent and will fade soon.
  disturbed_earth:
    behaviors:
    - object
    properties:
      name: Disturbed Earth
      description: Recently disturbed earth that will settle over time.
      readable: true
      immovable: true
      size: medium
      time_sensitive: true
      text: The earth has been recently disturbed. It will settle and become less
        obvious over time.
  ritual_preparations:
    behaviors:
    - object
    properties:
      name: Ritual Preparations
      description: Evidence of ongoing ritual preparations that will be completed
        soon.
      readable: true
      immovable: true
      size: medium
      time_sensitive: true
      text: The cult is preparing for a major ritual. The preparations will be complete
        soon.
  detectives_notebook:
    behaviors:
    - object
    properties:
      name: Detective's Notebook
      description: A worn leather notebook filled with clues, suspects, and case notes.
      readable: true
      pickupable: true
      size: small
      character_specific: detective_james
      text: Case notes on the Blackwater disappearances. Contains sketches of suspects
        and evidence.
  daughters_medicine:
    behaviors:
    - object
    properties:
      name: Daughter's Medicine
      description: Expensive medicine needed for Detective James's sick daughter.
      pickupable: true
      size: small
      character_specific: detective_james
      valuable: true
  confession_notes:
    behaviors:
    - object
    properties:
      name: Confession Notes
      description: Secret notes about the cult's activities that Father Marcus has
        been keeping.
      readable: true
      pickupable: true
      size: small
      character_specific: father_marcus
      text: Detailed notes about the cult's rituals and plans. Very dangerous if discovered.
  protection_money:
    behaviors:
    - object
    properties:
      name: Protection Money
      description: Gold coins that Gareth has been paying to The Raven for protection.
      pickupable: true
      size: small
      character_specific: gareth
      valuable: true
  cult_escape_kit:
    behaviors:
    - object
    properties:
      name: Cult Escape Kit
      description: A small kit with tools for escaping the cult's clutches.
      pickupable: true
      size: small
      character_specific: sarah
      survival: true
  ancient_artifacts:
    behaviors:
    - object
    properties:
      name: Ancient Artifacts
      description: Mysterious artifacts that Valdris carries with him.
      pickupable: true
      size: small
      character_specific: valdris
      magical: true
  town_treasury:
    behaviors:
    - object
    properties:
      name: Town Treasury
      description: The town's financial resources, controlled by the bank manager.
      immovable: true
      size: large
      resource: money
      amount: 1000
  guild_resources:
    behaviors:
    - object
    properties:
      name: Guild Resources
      description: Weapons, armor, and supplies controlled by the guild master.
      immovable: true
      size: large
      resource: equipment
      amount: 50
  information_network:
    behaviors:
    - object
    properties:
      name: Information Network
      description: The barkeep's network of informants and contacts.
      immovable: true
      size: medium
      resource: information
      reach: town_wide
  underground_network:
    behaviors:
    - object
    properties:
      name: Underground Network
      description: The Raven's criminal network and safe houses.
      immovable: true
      size: medium
      resource: security
      reach: regional
