actions:
  look:
    id: look
    name: look
    cost: 10
    description: Look around.
    parameters:
      - name: target
        type: string
        description: The name of the object or character to look at.
    requirements: []
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: look_at_target
        observers: ["player"]
  help:
    id: help
    name: help
    cost: 10
    description: Get help.
    parameters: []
    requirements: []
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: generate_help_message
        observers: ["player"]
  move:
    id: move
    name: move
    cost: 10
    description: Move in a specified direction.
    parameters:
      - name: direction
        type: string
        description: The direction to move (e.g., north, south, east, west).
    requirements:
      - type: exit_exists
        direction_param: direction
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: handle_move_action
        observers: ["player"]
  say:
    id: say
    name: say
    cost: 10
    description: Say something to other players in the room.
    parameters:
      - name: phrase
        type: string
        description: The phrase to say.
    requirements: []
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: handle_say_action
        observers: ["player", "room_players"]
  pass:
    id: pass
    name: pass
    cost: 0
    description: End your turn without taking any action.
    parameters: []
    requirements: []
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: handle_pass_action
        observers: ["player"]
  read:
    id: read
    name: read
    cost: 5
    description: Read text from an object (like signs, books, etc.).
    parameters:
      - name: object_name
        type: string
        description: The name of the object to read from.
        required: true
    requirements:
      - type: object_in_room
        object_name_param: object_name
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: handle_read_action
        observers: ["player", "room_players"]
