# Include the edition (which will include theme, which will include core)
includes:
  - "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow.yaml"

# Game settings
game_settings:
  num_rounds: 20
  manual: "../MANUAL.md"
  initial_ap_per_turn: 30 # High AP for strategic gameplay
# hints: [] # No hints configured - clean state for production

# List of AI players
players:
  - name: "Player_1"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Player_2"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Player_3"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Player_4"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Player_5"
    provider: "google"
    model: "gemini-2.5-flash"
