# V2 Game Configuration - Uses migrated v2 configs (only non-empty files)
includes:
  - "core_objects_migrated.yaml"
  - "core_actions_migrated.yaml"
  - "themes/fantasy/fantasy_objects_migrated.yaml"
  - "themes/fantasy/fantasy_actions_migrated.yaml"
  - "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow_rooms_migrated.yaml"
  - "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow_objects_migrated.yaml"
  - "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow_characters_migrated.yaml"

# Game settings
game_settings:
  num_rounds: 2
  manual: "../docs/MANUAL.md"
  initial_ap_per_turn: 30 # High AP for strategic gameplay

# List of AI players
players:
  - name: "Player_1"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Player_2"
    provider: "google"
    model: "gemini-2.5-flash"
