# Game settings
game_settings:
  num_rounds: 2
  core_config_path: "core.yaml"
  theme_config_path: "themes/fantasy/fantasy.yaml"
  edition_config_path: "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow.yaml"
  manual: "../MOTIVE_MANUAL.md"
  initial_ap_per_turn: 20 # Set initial AP per turn for testing
hints:
  # Test AP exhaustion feedback
  - hint_id: "test_ap_exhaustion_feedback"
    hint_action: "> pickup torch\n> pickup sword\n> pickup armor\n> look\n> move west\n> say hello\n> help"
    when:
      round: 1
      players: ["Arion"]

# List of AI players
players:
  - name: "Arion"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Lyra"
    provider: "google"
    model: "gemini-2.5-flash"
