# Include the edition (which will include theme, which will include core)
includes:
  - "themes/fantasy/editions/hearth_and_shadow/hearth_and_shadow.yaml"

# Game settings
game_settings:
  num_rounds: 2
  manual: "../MANUAL.md"
  initial_ap_per_turn: 20 # Set initial AP per turn for testing
# hints: [] # No hints configured - clean state for production

# List of AI players
players:
  - name: "Arion"
    provider: "google"
    model: "gemini-2.5-flash"

  - name: "Lyra"
    provider: "google"
    model: "gemini-2.5-flash"
