entity_definitions:
  torch:
    behaviors:
    - object
    attributes:
      name: Torch
      description: A simple wooden torch, useful for illumination.
    properties:
      is_lit: false
      light_source: true
  generic_fountain:
    behaviors:
    - object
    attributes:
      name: Fountain
      description: A basic fountain.
    properties:
      immovable: true
  generic_sign:
    behaviors:
    - object
    attributes:
      name: Sign
      description: A generic sign.
    properties: {}
  tiny_gem:
    behaviors:
    - object
    attributes:
      name: Tiny Gem
      description: A small, precious gem that sparkles in the light.
    properties:
      required_size: tiny
      requires_size: true
  small_potion:
    behaviors:
    - object
    attributes:
      name: Small Potion
      description: A small vial of healing potion.
    properties:
      required_size: small
      requires_size: true
  large_sword:
    behaviors:
    - object
    attributes:
      name: Large Sword
      description: A massive two-handed sword that requires great strength to wield.
    properties:
      required_size: large
      requires_size: true
  huge_boulder:
    behaviors:
    - object
    attributes:
      name: Huge Boulder
      description: An enormous boulder that only the strongest can move.
    properties:
      required_size: huge
      requires_size: true
  warrior_armor:
    behaviors:
    - object
    attributes:
      name: Warrior's Armor
      description: Heavy plate armor that only warriors can wear.
    properties:
      required_class: warrior
      requires_class: true
  mage_staff:
    behaviors:
    - object
    attributes:
      name: Mage's Staff
      description: A magical staff that only mages can channel power through.
    properties:
      required_class: mage
      requires_class: true
  rogue_dagger:
    behaviors:
    - object
    attributes:
      name: Rogue's Dagger
      description: A finely crafted dagger that only rogues can wield effectively.
    properties:
      required_class: rogue
      requires_class: true
  legendary_sword:
    behaviors:
    - object
    attributes:
      name: Legendary Sword
      description: A sword of immense power that only high-level heroes can wield.
    properties:
      required_level: 15
      requires_level: true
  epic_armor:
    behaviors:
    - object
    attributes:
      name: Epic Armor
      description: Legendary armor that requires great experience to wear.
    properties:
      required_level: 20
      requires_level: true
  paladin_sword:
    behaviors:
    - object
    attributes:
      name: Paladin's Sword
      description: A holy sword that requires both warrior class and high level.
    properties:
      required_class: warrior
      required_level: 10
      requires_class: true
      requires_level: true
  giant_warhammer:
    behaviors:
    - object
    attributes:
      name: Giant Warhammer
      description: A massive warhammer that requires both large size and warrior class.
    properties:
      required_size: large
      required_class: warrior
      requires_size: true
      requires_class: true
  elven_artifact:
    behaviors:
    - object
    attributes:
      name: Elven Artifact
      description: An ancient elven artifact that only elves of good alignment can
        use.
    properties:
      custom_constraints:
      - type: race
        value: elf
      - type: alignment
        value: good
  dragon_scale:
    behaviors:
    - object
    attributes:
      name: Dragon Scale
      description: A scale from an ancient dragon, only usable by those with dragon
        blood.
    properties:
      custom_constraints:
      - type: heritage
        value: dragon
      - type: level
        value: 25
  ancient_altar:
    behaviors:
    - object
    attributes:
      name: Ancient Altar
      description: A sacred altar that has been in this place for centuries.
    properties:
      immovable: true
      magically_bound: true
  town_statue:
    behaviors:
    - object
    attributes:
      name: Town Statue
      description: A large statue of the town's founder, too heavy to move.
    properties:
      immovable: true
      too_heavy: true
