# Include core configuration and fantasy theme components
includes:
  - "../../core.yaml"
  - "fantasy_objects.yaml"
  - "fantasy_actions.yaml"
  - "fantasy_characters.yaml"
  - "fantasy_rooms.yaml"

id: fantasy
name: Fantasy Theme