# Include the core configuration this theme is based on
includes:
  - "../../core.yaml"

id: fantasy
name: Fantasy Theme
object_types:
  torch:
    id: torch
    name: Torch
    description: A simple wooden torch, useful for illumination.
    tags: ["light_source"]
    properties:
      is_lit: false
  generic_fountain:
    id: generic_fountain
    name: Fountain
    description: A basic fountain.
    tags: ["immovable"]
    properties: {}
  generic_sign:
    id: generic_sign
    name: Sign
    description: A generic sign.
    tags: []
    properties: {}
  # Size-constrained objects
  tiny_gem:
    id: tiny_gem
    name: Tiny Gem
    description: A small, precious gem that sparkles in the light.
    tags: ["requires_size"]
    properties:
      required_size: "tiny"
  small_potion:
    id: small_potion
    name: Small Potion
    description: A small vial of healing potion.
    tags: ["requires_size"]
    properties:
      required_size: "small"
  large_sword:
    id: large_sword
    name: Large Sword
    description: A massive two-handed sword that requires great strength to wield.
    tags: ["requires_size"]
    properties:
      required_size: "large"
  huge_boulder:
    id: huge_boulder
    name: Huge Boulder
    description: An enormous boulder that only the strongest can move.
    tags: ["requires_size"]
    properties:
      required_size: "huge"
  # Class-constrained objects
  warrior_armor:
    id: warrior_armor
    name: Warrior's Armor
    description: Heavy plate armor that only warriors can wear.
    tags: ["requires_class"]
    properties:
      required_class: "warrior"
  mage_staff:
    id: mage_staff
    name: Mage's Staff
    description: A magical staff that only mages can channel power through.
    tags: ["requires_class"]
    properties:
      required_class: "mage"
  rogue_dagger:
    id: rogue_dagger
    name: Rogue's Dagger
    description: A finely crafted dagger that only rogues can wield effectively.
    tags: ["requires_class"]
    properties:
      required_class: "rogue"
  # Level-constrained objects
  legendary_sword:
    id: legendary_sword
    name: Legendary Sword
    description: A sword of immense power that only high-level heroes can wield.
    tags: ["requires_level"]
    properties:
      required_level: 15
  epic_armor:
    id: epic_armor
    name: Epic Armor
    description: Legendary armor that requires great experience to wear.
    tags: ["requires_level"]
    properties:
      required_level: 20
  # Multi-constraint objects
  paladin_sword:
    id: paladin_sword
    name: Paladin's Sword
    description: A holy sword that requires both warrior class and high level.
    tags: ["requires_class", "requires_level"]
    properties:
      required_class: "warrior"
      required_level: 10
  giant_warhammer:
    id: giant_warhammer
    name: Giant Warhammer
    description: A massive warhammer that requires both large size and warrior class.
    tags: ["requires_size", "requires_class"]
    properties:
      required_size: "large"
      required_class: "warrior"
  # Custom constraint objects
  elven_artifact:
    id: elven_artifact
    name: Elven Artifact
    description: An ancient elven artifact that only elves of good alignment can use.
    tags: []
    properties:
      custom_constraints:
        - type: "race"
          value: "elf"
        - type: "alignment"
          value: "good"
  dragon_scale:
    id: dragon_scale
    name: Dragon Scale
    description: A scale from an ancient dragon, only usable by those with dragon blood.
    tags: []
    properties:
      custom_constraints:
        - type: "heritage"
          value: "dragon"
        - type: "level"
          value: 25
  # Immovable objects
  ancient_altar:
    id: ancient_altar
    name: Ancient Altar
    description: A sacred altar that has been in this place for centuries.
    tags: ["immovable", "magically_bound"]
    properties: {}
  town_statue:
    id: town_statue
    name: Town Statue
    description: A large statue of the town's founder, too heavy to move.
    tags: ["immovable", "too_heavy"]
    properties: {}
actions:
  pickup:
    id: pickup
    name: pickup
    cost: 10
    description: Pick up an object.
    parameters:
      - name: object_name
        type: string
        description: The name of the object to pick up.
    requirements:
      - type: object_in_room
        object_name_param: object_name
    effects:
      - type: code_binding
        function_module: motive.hooks.core_hooks
        function_name: handle_pickup_action
        observers: ["player"]
  light_torch:
    id: light_torch
    name: light torch
    cost: 10
    description: Light a torch you are holding.
    parameters:
      - name: object_name
        type: string
        description: The name of the torch to light.
    requirements:
      - type: player_has_object_in_inventory
        object_name_param: object_name
      - type: object_property_equals
        object_name_param: object_name
        property: is_lit
        value: false
    effects:
      - type: set_property
        target_type: object
        target_id_param: object_name
        property: is_lit
        value: true
      - type: generate_event
        message: "{{player_name}} lights the {{object_name}}."
        observers: ["room_players"]
character_types:
  hero:
    id: hero
    name: Hero
    backstory: A brave adventurer.
    motive: Defeat the evil sorcerer.
